version: "3.9"

services:
  cats_db:
    image: yzh44yzh/wg_forge_backend_env:1.1
    ports:
      - "5432:5432"
    container_name: db

  cats_app:
    build: ./
    depends_on:
      - cats_db
    container_name: cats_app
    ports:
      - "8080:8080"

  nginx:
    image: nginx:1.25.1-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - cats_app
